### ISSUE TITLE
Revisit PIN verification

### ISSUE THREAD

**Issue by robin-nitrokey** [Nitrokey/opcard-rs#16]
Currently (#15), we store the unencrypted PIN in the persistent state.  This should either be outsourced to the secure element or replaced with a hash (that could be handled by Trussed) and the PIN length (required for some OpenPGP operations).

**Comment by EliteTK** [comment]
I am not familiar with the design of the NK3 or how these kinds of devices work, so I apologise in advance for my ignorance of how this all works.

I was researching what the intended features were for the NK3's NFC facilities. Specifically I was curious if, like the yubikey neo (and I believe yubikey 5), I would be able to use NFC to decrypt gpg encrypted passwords on my phone (using Password Store and OpenKechain) as this is a major feature for me and I have been seriously considering the NK3 as a successor to my YKN.

By the sounds of it, the intention is to require use of SE050 to store the PIN thereby preventing this usecase (due to the power requirements of the secure element).

Am I correct in my understanding? If the pin was not stored within SE050, would it be possible to use NK3 as a NFC smartcard? If so, would it instead be possible (to mitigate brute force attacks) to simply implement a 3 attempt pin lockout?

Thanks in advance.

**Comment by robin-nitrokey** [comment]
@EliteTK Generally speaking, our design goal for the Nitrokey 3 is to let users configure whether they want to use the SE050 (higher security) or software implementations (usable over NFC, easier to review and audit) where applicable.

We will also consider this when adding SE050 support to opcard.  As the implementation details are abstracted by the Trussed framework, it will likely be possible to configure opcard to not use the SE050.

By the way, there already is a PIN retry counter (3) as a protection against brute force attacks.  The SE050 adds additional protection against attackers with access to the hardware and the possibility to read out the flash memory.

**Comment by robin-nitrokey** [comment]
To address your specific point regarding NFC usage, I should add that there are other factors than only the SE050, e. g. access to the external flash (which also requires more power than NFC can provide).  We will evaluate this but it is not clear yet if, how and when it will be implemented.

**Comment by robin-nitrokey** [comment]
Fixed by using trussed-auth in https://github.com/Nitrokey/opcard-rs/pull/125.
